
[ClassVersion("1.0.0"), FriendlyName("cWebAppPool")]
class SEEK_cWebAppPool : OMI_BaseResource
{
    [Key, Description("Name of the Web Application Pool")] String Name;
    [Key, Description("Name of the Web Site or Web Application using the pool")] String ApplicationName;
    [Write, Description("Web Application Pool Present/Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("State of Web Application Pool"), ValueMap{"Started","Stopped"}, Values{"Started","Stopped"}] String State;
    [write,ValueMap{"v4.0","v2.0","No Managed Code"},Values{"v4.0","v2.0",""}] string ManagedRuntimeVersion;
    [write,ValueMap{"Integrated","Classic"},Values{"Integrated","Classic"}] string ManagedPipelineMode;
    [write,ValueMap{"True","False"},Values{"true","false"}] string Enable32BitAppOnWin64;
    [write,ValueMap{"ApplicationPoolIdentity","LocalSystem","LocalService","NetworkService","SpecificUser"},Values{"ApplicationPoolIdentity","LocalSystem","LocalService","NetworkService","SpecificUser"}] string IdentityType;
    [write] string UserName;
    [write] string Password;
};

