[ClassVersion("1.0.0"), FriendlyName("cPrivateMsmqQueue")]
class SEEK_cPrivateMsmqQueue : OMI_BaseResource
{
    [Key, Description("Name of the queue")] String Name;
    [Write, Description("Queue Present/Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [write,ValueMap{"True","False"},Values{"true","false"}] string Transactional;
};

