name: "Lock Closed Issues and PRs"

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/dessant/lock-threads
      - uses: dessant/lock-threads@v5
        with:
          exclude-issue-closed-before: "2024-06-01"
          issue-inactive-days: 30
          issue-lock-reason: "resolved"
          pr-inactive-days: 30
          exclude-pr-closed-before: "2024-06-01"
          pr-lock-reason: "resolved"
          discussion-inactive-days: 60



